c-database-mode: MySQL # or Local
c-database:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  database: "cococo"

c-api:
  c-api-enable: false
  c-api-host: 0.0.0.0
  c-api-port: 1558
  c-api-key: ""

default-language: en_US